### ISSUE TITLE
[CMS] We need to know how many testcases are there for each problem, even if no submission has been submitted yet.

### ISSUE THREAD

**Issue by nyngwang** [Judge-Girl/Judge-Girl#375]
As shown below, current we can only know how many testcases are there when there is a submission. We need to draw the barchart even when no submission.

![image](https://user-images.githubusercontent.com/24765272/122896937-25e37080-d37c-11eb-8460-10949b461930.png)

**Comment by Johnny850807** [comment]
get problem by id api
